#!/usr/bin/env python3
"""PreToolUse hook: block edits to generated/locked artifacts.

These paths must not be hand-edited:
  - testapp/         Copier-generated, gitignored. Regenerate via `just testapp`.
  - uv.lock          Regenerated by `uv sync` — never hand-edit.
  - checkpoints.db   Dev SQLite, gitignored.

Exits 2 (blocking error) if a write target matches any of these.
"""

from __future__ import annotations

import json
import sys

PROTECTED = ("testapp/", "uv.lock", "checkpoints.db")


def main() -> int:
    try:
        data = json.load(sys.stdin)
    except json.JSONDecodeError:
        return 0

    if data.get("tool_name") not in ("Edit", "Write", "MultiEdit"):
        return 0

    path = (data.get("tool_input") or {}).get("file_path")
    if not isinstance(path, str):
        return 0

    for needle in PROTECTED:
        if needle in path:
            sys.stderr.write(
                f"blocked: {path} matches protected path '{needle}'.\n"
                "  - testapp/       is generated by Copier; regenerate via `just testapp`\n"
                "  - uv.lock        is regenerated by `uv sync`; never hand-edit\n"
                "  - checkpoints.db is dev SQLite, gitignored\n"
            )
            return 2

    return 0


if __name__ == "__main__":
    sys.exit(main())
