"""CLI utilities for langgraph-kit.

Usage::

    python -m langgraph_kit.cli new my-agent
    python -m langgraph_kit.cli new my-agent --output-dir ./agents
    python -m langgraph_kit.cli new my-agent --force   # overwrite existing
    python -m langgraph_kit.cli list
    python -m langgraph_kit.cli examples list
    python -m langgraph_kit.cli examples run quickstart_echo
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path
from textwrap import dedent

_AGENT_TEMPLATE = '''\
"""{{agent_title}} agent.

Auto-generated by ``python -m langgraph_kit.cli new {{agent_id}}``.
Customize the prompt sections, worker definitions, and tool selection below.
"""

from __future__ import annotations

import logging
from typing import Any

from langgraph_kit._config import get_config
from langgraph_kit.core.context_management.pressure import PressureMonitor
from langgraph_kit.core.memory.persistent import PersistentMemoryManager
from langgraph_kit.core.prompt_assembly.activation import ACTIVATION_SECTIONS
from langgraph_kit.core.prompt_assembly.composer import PromptComposer
from langgraph_kit.core.prompt_assembly.context_providers import (
    MemoryContextProvider,
    ThreadContextProvider,
    ToolContextProvider,
)
from langgraph_kit.core.prompt_assembly.sections import (
    PromptSection,
    SectionRegistry,
    SectionStability,
)
from langgraph_kit.core.tools.registry import ToolRegistry
from langgraph_kit.graphs import (
    build_backend_factory,
    build_command_dispatcher,
    build_middleware_stack,
    register_standard_tools,
)
from langgraph_kit.llm import build_llm

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Prompt sections — customize for your agent's personality and role
# ---------------------------------------------------------------------------

_SECTIONS = [
    PromptSection(
        id="core_identity",
        content=(
            "You are {{agent_title}}, a specialized AI assistant.\\n\\n"
            "Operate carefully and deliberately. Use tools only when they "
            "materially advance the task."
        ),
        stability=SectionStability.STABLE,
        priority=100,
    ),
]

# ---------------------------------------------------------------------------
# Worker definitions — add specialized sub-agents here
# ---------------------------------------------------------------------------

WORKER_DEFINITIONS: list[dict[str, Any]] = [
    {
        "name": "researcher",
        "description": "Investigate and gather information.",
        "system_prompt": (
            "You are a research specialist. Investigate thoroughly and "
            "report findings in a structured format."
        ),
    },
]


# ---------------------------------------------------------------------------
# Build function
# ---------------------------------------------------------------------------


def build_{{fn_name}}(
    checkpointer: Any, store: Any, *, mcp_tools: list[Any] | None = None
) -> Any:
    """Build the {{agent_title}} agent."""
    from deepagents import (
        create_deep_agent,  # pyright: ignore[reportMissingModuleSource]
    )

    llm = build_llm()
    memory_mgr = PersistentMemoryManager(
        store, embedding_fn=get_config().memory_embedding_fn
    )

    # --- Tools ---
    tool_registry = ToolRegistry()
    register_standard_tools(
        tool_registry,
        memory_mgr,
        store,
        parent_thread_id="{{agent_id}}-global",
        mcp_tools=mcp_tools,
    )

    # --- Prompt assembly ---
    section_registry = SectionRegistry()
    section_registry.register_many(_SECTIONS)
    section_registry.register_many(ACTIVATION_SECTIONS)

    tool_guidance = tool_registry.collect_prompt_fragments()
    if tool_guidance:
        section_registry.register(
            PromptSection(
                id="tool_guidance",
                content=tool_guidance,
                stability=SectionStability.VOLATILE,
                priority=50,
            )
        )

    providers = [
        ThreadContextProvider(),
        MemoryContextProvider(),
        ToolContextProvider(),
    ]
    composer = PromptComposer(section_registry, providers)

    # --- Commands + middleware ---
    pressure_monitor = PressureMonitor()
    command_dispatcher = build_command_dispatcher(
        memory_mgr, pressure_monitor, tool_registry=tool_registry
    )
    middleware, _ = build_middleware_stack(
        llm=llm,
        memory_mgr=memory_mgr,
        pressure_monitor=pressure_monitor,
        command_dispatcher=command_dispatcher,
    )

    # --- Build ---
    # "deferred_tools" is intentionally omitted: register_standard_tools
    # returns an empty DeferredToolRegistry by default, and activating
    # the deferred_tools_awareness section against an empty registry
    # tells the LLM to call tool_search for capabilities that do not
    # exist. Add "deferred_tools" back to this set once you populate
    # the registry (see langgraph_kit.core.tools.deferred).
    system_prompt = composer.compose_sections_only(
        conditions={"memory", "orchestration", "skills", "async_tasks"}
    )

    graph = create_deep_agent(
        model=llm,
        tools=tool_registry.compile_tools(),
        system_prompt=system_prompt,
        middleware=middleware,
        subagents=WORKER_DEFINITIONS,
        checkpointer=checkpointer,
        store=store,
        backend=build_backend_factory("{{agent_id}}"),
        name="{{agent_id}}",
    )
    return graph, command_dispatcher
'''


def _generate_agent(
    agent_id: str, output_dir: Path | None = None, *, force: bool = False
) -> Path:
    """Generate an agent file from template.

    Refuses to overwrite an existing file unless ``force=True`` — without
    the guard, ``new my-agent`` run twice silently clobbers customization.
    """
    fn_name = agent_id.replace("-", "_")
    agent_title = agent_id.replace("-", " ").title()

    content = _AGENT_TEMPLATE
    content = content.replace("{{agent_id}}", agent_id)
    content = content.replace("{{fn_name}}", fn_name)
    content = content.replace("{{agent_title}}", agent_title)

    out_dir = output_dir or Path.cwd()
    out_file = out_dir / f"{fn_name}.py"
    if out_file.exists() and not force:
        raise FileExistsError(
            f"{out_file} already exists. Re-run with --force to overwrite, "
            f"or pick a different agent_id."
        )
    out_file.write_text(content, encoding="utf-8")
    return out_file


def _out(text: str) -> None:
    sys.stdout.write(text + "\n")


# ---------------------------------------------------------------------------
# Examples discovery
# ---------------------------------------------------------------------------


def _examples_dir() -> Path | None:
    """Locate the repo-root ``examples/`` directory, or ``None`` if missing.

    The kit's wheel doesn't yet ship examples (they live at the repo
    root, not under ``src/langgraph_kit/``). When run from a source
    checkout, walk up from the installed package to find them. When
    run from a PyPI install, this returns None and the caller surfaces
    a clear "clone the repo" message — see issue #61.
    """
    candidate = Path(__file__).resolve().parent.parent.parent / "examples"
    return candidate if candidate.is_dir() else None


def _example_pitch(path: Path) -> str:
    """Return the first non-blank docstring line as the example's pitch."""
    try:
        head = path.read_text(encoding="utf-8")[:2000]
    except OSError:
        return ""
    # Capture the docstring delimited by ``"""..."""``; the first line is
    # the pitch.
    match = re.search(r'"""(.+?)"""', head, re.DOTALL)
    if not match:
        return ""
    body = match.group(1).strip()
    return body.splitlines()[0] if body else ""


def _list_examples(examples_dir: Path) -> list[Path]:
    """Return the discoverable examples, sorted alphabetically."""
    return sorted(
        p
        for p in examples_dir.glob("*.py")
        if p.name != "run_all.py" and not p.name.startswith("_")
    )


def _cmd_examples_list() -> int:
    examples_dir = _examples_dir()
    if examples_dir is None:
        sys.stderr.write(
            "examples/ directory not found. Examples ship from the source "
            "checkout — clone https://github.com/allada-homelab/langgraph-kit "
            "and run from there.\n"
        )
        return 1
    paths = _list_examples(examples_dir)
    _out(f"{len(paths)} example(s) in {examples_dir}:")
    for path in paths:
        pitch = _example_pitch(path)
        # Right-pad the name so pitches line up; widest current name is ~30.
        _out(f"  {path.stem:<32} {pitch}")
    return 0


def _cmd_examples_run(name: str, *, real_llm: bool = False) -> int:
    examples_dir = _examples_dir()
    if examples_dir is None:
        sys.stderr.write(
            "examples/ directory not found. Examples ship from the source "
            "checkout — clone the repo to use ``examples run``.\n"
        )
        return 1
    target = examples_dir / f"{name}.py"
    if not target.is_file():
        sys.stderr.write(
            f"No example named {name!r}. Run ``examples list`` to see options.\n"
        )
        return 2

    repo_root = examples_dir.parent
    env = dict(os.environ)
    env.setdefault("LANGGRAPH_KIT_EXAMPLES_LLM", "real" if real_llm else "scripted")
    completed = subprocess.run(  # noqa: S603 — fixed argv, no shell, internal use
        [sys.executable, "-m", f"examples.{name}"],
        check=False,
        cwd=repo_root,
        env=env,
    )
    return completed.returncode


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        prog="langgraph-kit",
        description="langgraph-kit CLI utilities",
    )
    sub = parser.add_subparsers(dest="command")

    # new command
    new_parser = sub.add_parser("new", help="Generate a new agent from template")
    new_parser.add_argument("agent_id", help="Agent ID (e.g. my-research-agent)")
    new_parser.add_argument(
        "--output-dir", "-o", type=Path, help="Output directory (default: cwd)"
    )
    new_parser.add_argument(
        "--force",
        "-f",
        action="store_true",
        help="Overwrite an existing file",
    )

    # list command
    sub.add_parser("list", help="List available agent templates")

    # examples command (with nested list / run subcommands)
    examples_parser = sub.add_parser(
        "examples", help="Discover and run the bundled feature examples"
    )
    ex_sub = examples_parser.add_subparsers(dest="examples_command")
    ex_sub.add_parser("list", help="List discoverable examples")
    run_parser = ex_sub.add_parser("run", help="Run an example by name")
    run_parser.add_argument("name", help="Example file name without extension")
    run_parser.add_argument(
        "--real-llm",
        action="store_true",
        help="Use the real LLM (requires AGENT_LLM_API_KEY)",
    )

    args = parser.parse_args()

    if args.command == "new":
        try:
            path = _generate_agent(args.agent_id, args.output_dir, force=args.force)
        except FileExistsError as exc:
            sys.stderr.write(f"Error: {exc}\n")
            sys.exit(1)
        _out(f"Generated agent: {path}")
        _out(
            dedent(f"""\
            Next steps:
            1. Move {path.name} to your graphs/ directory
            2. Customize the prompt sections and worker definitions
            3. Register in graphs/__init__.py:
               from langgraph_kit.graphs.{path.stem} import build_{path.stem}
               graph, dispatcher = build_{path.stem}(checkpointer, store)
               register("{args.agent_id}", graph, command_dispatcher=dispatcher)
        """)
        )
    elif args.command == "list":
        _out("Available templates:")
        _out("  default — Full-featured agent with memory, tools, commands, middleware")
    elif args.command == "examples":
        if args.examples_command == "list":
            sys.exit(_cmd_examples_list())
        elif args.examples_command == "run":
            sys.exit(_cmd_examples_run(args.name, real_llm=args.real_llm))
        else:
            examples_parser.print_help()
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
