"""CLI utilities for langgraph-kit.

Usage::

    python -m langgraph_kit.cli new my-agent
    python -m langgraph_kit.cli new my-agent --output-dir ./agents
    python -m langgraph_kit.cli new my-agent --force   # overwrite existing
    python -m langgraph_kit.cli list
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from textwrap import dedent

_AGENT_TEMPLATE = '''\
"""{{agent_title}} agent.

Auto-generated by ``python -m langgraph_kit.cli new {{agent_id}}``.
Customize the prompt sections, worker definitions, and tool selection below.
"""

from __future__ import annotations

import logging
from typing import Any

from langgraph_kit.core.context_management.pressure import PressureMonitor
from langgraph_kit.core.memory.persistent import PersistentMemoryManager
from langgraph_kit.core.prompt_assembly.activation import ACTIVATION_SECTIONS
from langgraph_kit.core.prompt_assembly.composer import PromptComposer
from langgraph_kit.core.prompt_assembly.context_providers import (
    MemoryContextProvider,
    ThreadContextProvider,
    ToolContextProvider,
)
from langgraph_kit.core.prompt_assembly.sections import (
    PromptSection,
    SectionRegistry,
    SectionStability,
)
from langgraph_kit.core.tools.registry import ToolRegistry
from langgraph_kit.graphs import (
    build_backend_factory,
    build_command_dispatcher,
    build_middleware_stack,
    register_standard_tools,
)
from langgraph_kit.llm import build_llm

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Prompt sections — customize for your agent's personality and role
# ---------------------------------------------------------------------------

_SECTIONS = [
    PromptSection(
        id="core_identity",
        content=(
            "You are {{agent_title}}, a specialized AI assistant.\\n\\n"
            "Operate carefully and deliberately. Use tools only when they "
            "materially advance the task."
        ),
        stability=SectionStability.STABLE,
        priority=100,
    ),
]

# ---------------------------------------------------------------------------
# Worker definitions — add specialized sub-agents here
# ---------------------------------------------------------------------------

WORKER_DEFINITIONS: list[dict[str, Any]] = [
    {
        "name": "researcher",
        "description": "Investigate and gather information.",
        "system_prompt": (
            "You are a research specialist. Investigate thoroughly and "
            "report findings in a structured format."
        ),
    },
]


# ---------------------------------------------------------------------------
# Build function
# ---------------------------------------------------------------------------


def build_{{fn_name}}(
    checkpointer: Any, store: Any, *, mcp_tools: list[Any] | None = None
) -> Any:
    """Build the {{agent_title}} agent."""
    from deepagents import (
        create_deep_agent,  # pyright: ignore[reportMissingModuleSource]
    )

    llm = build_llm()
    memory_mgr = PersistentMemoryManager(store)

    # --- Tools ---
    tool_registry = ToolRegistry()
    register_standard_tools(
        tool_registry,
        memory_mgr,
        store,
        parent_thread_id="{{agent_id}}-global",
        mcp_tools=mcp_tools,
    )

    # --- Prompt assembly ---
    section_registry = SectionRegistry()
    section_registry.register_many(_SECTIONS)
    section_registry.register_many(ACTIVATION_SECTIONS)

    tool_guidance = tool_registry.collect_prompt_fragments()
    if tool_guidance:
        section_registry.register(
            PromptSection(
                id="tool_guidance",
                content=tool_guidance,
                stability=SectionStability.VOLATILE,
                priority=50,
            )
        )

    providers = [
        ThreadContextProvider(),
        MemoryContextProvider(),
        ToolContextProvider(),
    ]
    composer = PromptComposer(section_registry, providers)

    # --- Commands + middleware ---
    pressure_monitor = PressureMonitor()
    command_dispatcher = build_command_dispatcher(
        memory_mgr, pressure_monitor, tool_registry=tool_registry
    )
    middleware, _ = build_middleware_stack(
        llm=llm,
        memory_mgr=memory_mgr,
        pressure_monitor=pressure_monitor,
        command_dispatcher=command_dispatcher,
    )

    # --- Build ---
    # "deferred_tools" is intentionally omitted: register_standard_tools
    # returns an empty DeferredToolRegistry by default, and activating
    # the deferred_tools_awareness section against an empty registry
    # tells the LLM to call tool_search for capabilities that do not
    # exist. Add "deferred_tools" back to this set once you populate
    # the registry (see langgraph_kit.core.tools.deferred).
    system_prompt = composer.compose_sections_only(
        conditions={"memory", "orchestration", "skills", "async_tasks"}
    )

    graph = create_deep_agent(
        model=llm,
        tools=tool_registry.compile_tools(),
        system_prompt=system_prompt,
        middleware=middleware,
        subagents=WORKER_DEFINITIONS,
        checkpointer=checkpointer,
        store=store,
        backend=build_backend_factory("{{agent_id}}"),
        name="{{agent_id}}",
    )
    return graph, command_dispatcher
'''


def _generate_agent(
    agent_id: str, output_dir: Path | None = None, *, force: bool = False
) -> Path:
    """Generate an agent file from template.

    Refuses to overwrite an existing file unless ``force=True`` — without
    the guard, ``new my-agent`` run twice silently clobbers customization.
    """
    fn_name = agent_id.replace("-", "_")
    agent_title = agent_id.replace("-", " ").title()

    content = _AGENT_TEMPLATE
    content = content.replace("{{agent_id}}", agent_id)
    content = content.replace("{{fn_name}}", fn_name)
    content = content.replace("{{agent_title}}", agent_title)

    out_dir = output_dir or Path.cwd()
    out_file = out_dir / f"{fn_name}.py"
    if out_file.exists() and not force:
        raise FileExistsError(
            f"{out_file} already exists. Re-run with --force to overwrite, "
            f"or pick a different agent_id."
        )
    out_file.write_text(content, encoding="utf-8")
    return out_file


def _out(text: str) -> None:
    sys.stdout.write(text + "\n")


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        prog="langgraph-kit",
        description="langgraph-kit CLI utilities",
    )
    sub = parser.add_subparsers(dest="command")

    # new command
    new_parser = sub.add_parser("new", help="Generate a new agent from template")
    new_parser.add_argument("agent_id", help="Agent ID (e.g. my-research-agent)")
    new_parser.add_argument(
        "--output-dir", "-o", type=Path, help="Output directory (default: cwd)"
    )
    new_parser.add_argument(
        "--force",
        "-f",
        action="store_true",
        help="Overwrite an existing file",
    )

    # list command
    sub.add_parser("list", help="List available agent templates")

    args = parser.parse_args()

    if args.command == "new":
        try:
            path = _generate_agent(args.agent_id, args.output_dir, force=args.force)
        except FileExistsError as exc:
            sys.stderr.write(f"Error: {exc}\n")
            sys.exit(1)
        _out(f"Generated agent: {path}")
        _out(
            dedent(f"""\
            Next steps:
            1. Move {path.name} to your graphs/ directory
            2. Customize the prompt sections and worker definitions
            3. Register in graphs/__init__.py:
               from langgraph_kit.graphs.{path.stem} import build_{path.stem}
               graph, dispatcher = build_{path.stem}(checkpointer, store)
               register("{args.agent_id}", graph, command_dispatcher=dispatcher)
        """)
        )
    elif args.command == "list":
        _out("Available templates:")
        _out("  default — Full-featured agent with memory, tools, commands, middleware")
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
